AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy a static website using AWS S3 Bucket

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
    DeletionPolicy: Retain

Outputs:
  WebsiteURL:
    Value: !GetAtt
      - S3Bucket
      - WebsiteURL
    Description: URL for website deployed on S3
